name: release
on:
  push:
    tags: ["v*"]

jobs:
  build-and-release-win:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv sync

      # タグ（v1.2.3）から __version__ と version.rc を生成
      - name: Generate version files
        shell: pwsh
        run: |
          $ver = "${{ github.ref_name }}".TrimStart("v")
          uv run python scripts/write_version.py $ver
          Get-Content packaging/version.rc.txt

      # PyInstaller（onedir / no upx / clean）
      - name: Build (PyInstaller)
        shell: pwsh
        run: uv run pyinstaller packaging/app.spec --clean --noupx

      # ZIP化（dist\myapp\* をひとまとめ）
      - name: Zip
        shell: pwsh
        run: Compress-Archive -Path dist\myapp\* -DestinationPath dist\myapp-${{ github.ref_name }}-win64.zip -Force

      # Release Assetsへ添付（タグ作成で自動的にリリースも作成）
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/myapp-${{ github.ref_name }}-win64.zip
